name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install clickable
        run: |
          sudo apt install adb git python3 python3-pip python3-setuptools
          pip3 install --user clickable-ut --upgrade
          echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc

      - name: Build bw libraries
        run: ./dev/build-bw.sh

      - name: Build Warden
        run: clickable build --output dist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
