name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v18

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install clickable
        run: |
          docker --version
          sudo apt install adb git python3 python3-pip python3-setuptools
          pip3 install --user clickable-ut==7.10.0 --upgrade
          echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc

      - name: Build bw libraries
        run: ./dev/build-bw.sh

      - name: Build Warden
        run: clickable build --output dist

      - uses: actions/upload-artifact@v3
        with:
          name: click
          path: dist/*

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build/all/app/install/

      # Tests

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install test dependencies
        working-directory: tests
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run tests
        working-directory: tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright-report/
